// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl_JfVJmEkux1eGzlS-l4OxLhrk_WJi78',
    appId: '1:214751930233:web:7b4e51d39b68bc985c31a8',
    messagingSenderId: '214751930233',
    projectId: 'healthcareapp-361d0',
    authDomain: 'healthcareapp-361d0.firebaseapp.com',
    databaseURL: 'https://healthcareapp-361d0-default-rtdb.firebaseio.com',
    storageBucket: 'healthcareapp-361d0.firebasestorage.app',
    measurementId: 'G-8V0P86CPJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyAaY__AdjrQ5hURMaLf_TFg1jOdchSo',
    appId: '1:214751930233:android:7723b03182c02b995c31a8',
    messagingSenderId: '214751930233',
    projectId: 'healthcareapp-361d0',
    databaseURL: 'https://healthcareapp-361d0-default-rtdb.firebaseio.com',
    storageBucket: 'healthcareapp-361d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0qc9cmjNehSKVXnJDj9PilZxGCvTEW0Q',
    appId: '1:214751930233:ios:5dacbc396d4613fd5c31a8',
    messagingSenderId: '214751930233',
    projectId: 'healthcareapp-361d0',
    databaseURL: 'https://healthcareapp-361d0-default-rtdb.firebaseio.com',
    storageBucket: 'healthcareapp-361d0.firebasestorage.app',
    iosBundleId: 'com.example.healthcarenew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0qc9cmjNehSKVXnJDj9PilZxGCvTEW0Q',
    appId: '1:214751930233:ios:5dacbc396d4613fd5c31a8',
    messagingSenderId: '214751930233',
    projectId: 'healthcareapp-361d0',
    databaseURL: 'https://healthcareapp-361d0-default-rtdb.firebaseio.com',
    storageBucket: 'healthcareapp-361d0.firebasestorage.app',
    iosBundleId: 'com.example.healthcarenew',
  );
}
